---
- name: Install Docker on Debian 12
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    docker_user: k8suser

  tasks:
  
    - name: Uninstall old Docker packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker service status
      command: systemctl is-active docker
      register: docker_status
      failed_when: docker_status.stdout != "active"
      changed_when: false

    - name: Verify Docker socket exists
      stat:
        path: /var/run/docker.sock
      register: docker_sock

    - name: Show socket info
      debug:
        var: docker_sock.stat.path

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Run Docker info as non-root user
      command: docker info
      become_user: "{{ docker_user }}"
      register: docker_info
      failed_when: docker_info.rc != 0